package com.fitness.tracker.dto;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class GoalDTO {
    private Long id;
    
    @NotNull(message = "Target weight is required")
    @Min(value = 1, message = "Target weight must be positive")
    private Double targetWeight;
    
    private Integer dailyCalorieGoal; // Auto-generated by AI if not provided
    
    @NotNull(message = "Target date is required to compute goals")
    private LocalDate targetDate;

    @Min(value = 50, message = "Height must be realistic")
    private Double height;
    
    @Min(value = 20, message = "Current weight must be realistic")
    private Double currentWeight;
}
